config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  root "users#index"
    
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, [Post, Comment]

    return unless user.present?

    can :manage, [Post, Comment], author: user

    return unless user.admin?

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :increment_comment_count

  def increment_comment_count
    post.increment!(:comments_counter)
  end

  private :increment_comment_count
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :increment_like_count

  def increment_like_count
    post.increment!(:likes_counter)
  end

  private :increment_like_count
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  after_initialize :set_default

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  after_create :increment_user_post_count

  # Increment user posts count
  def increment_user_post_count
    author.increment!(:posts_counter)
  end

  # Return user most recent comments
  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def set_default
    self.likes_counter = 0 if likes_counter.nil?
    self.comments_counter = 0 if comments_counter.nil?
  end

  private :increment_user_post_count
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy

  after_initialize :set_default

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  # Most recent posts
  def recent_posts
    posts.first(3)
  end

  def set_default
    self.posts_counter = 0 if posts_counter.nil?
  end

  ROLES = %i[admin user].freeze

  def admin?
    role == :admin
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ActionController::API
  def index
    post = Post.find(params[:post_id])
    comments = post.comments
    render json: comments, status: :ok
  end

  def create
    post = Post.find(params[:post_id])
    comment = post.comments.new(comment_params)

    if comment.save
      render json: comment, status: :ok
    else
      render json: comment.errors, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ActionController::API
  def index
    user = User.find(params[:user_id])
    posts = user.posts
    render json: posts, status: :ok
  end

  def show
    post = Post.find(params[:id])
    render json: post, status: :ok
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ActionController::API
  def index
    users = User.all
    render json: users, status: :ok
  end

  def show
    user = User.find(params[:id])
    render json: user, status: :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Catch all CanCan errors and alert the user of the exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio photo email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name bio photo email password current_password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]

    respond_to do |format|
      if @comment.save
        format.html do
          redirect_to user_post_path(@comment.author, @comment.post), notice: 'Successfully added a comment'
        end
      else
        @user = Post.find(params[:user_id])
        @post = Post.find(params[:post_id])
        flash[:error] = @comment.errors.full_messages
        format.html { redirect_to user_post_path(@user, @post) }
      end
    end
  end

  def destroy
    post = Post.find(params[:post_id])
    comment = post.comments.find(params[:id])
    comment.destroy
    post.decrement!(:comments_counter)
    respond_to do |format|
      format.html { redirect_to user_post_path(post.author, post), notice: 'Comment was successfully destroyed' }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new
    @like.post_id = params[:post_id]

    respond_to do |format|
      if @like.save
        format.html { redirect_to user_post_path(@like.author, @like.post), notice: 'You have liked this post' }
      else
        @user = Post.find(params[:user_id])
        @post = Post.find(params[:post_id])
        flash[:error] = @like.errors.full_messages
        format.html { redirect_to user_post_path(@user, @post) }
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.includes(posts: [:comments]).find(params[:user_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to user_posts_path(current_user.id), notice: 'successfully added a post' }
      else
        flash[:error] = @post.errors.full_messages
        format.html { redirect_to new_user_post_path(current_user.id) }
      end
    end
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.comments.includes(:user)
  end

  def destroy
    user = User.find(params[:user_id])
    post = user.posts.find(params[:id])
    post.destroy
    user.decrement!(:posts_counter)

    respond_to do |format|
      format.html { redirect_to user_posts_path(user.id), notice: 'Successfully removed post' }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post = @user.recent_posts
  end
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= render 'shared/flash' %>
<%= form_with model: Comment, url: user_post_comments_path(@user, @post) do |form| %>
  <div class="form-control">
    <%= form.label :text, "Text" %>
    <%= form.text_area :text, size: "70x15" %>
  </div>
  <div class="form-submit">
    <%= form.submit "Add Comment" %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: @post, url: user_posts_path do |form| %>
  <div class="form-control">
    <%= form.label :title, "Title" %>
    <%= form.text_field :title %>
  </div>
  <div class="form-control">
    <%= form.label :text, "Text" %>
    <%= form.text_area :text, size: "70x15" %>
  </div>
  <div class="form-submit">
    <%= form.submit "Create Post" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="user-specific-post">
  <%= render partial: "users/user_info", locals: {user: @user} %>

  <div class="post-info">
    <% @user.posts.each do |post| %>
      <%= render partial: "users/user_post", locals: {post: post} %>

      <div class="comments border">
        <% post.recent_comments.each do |comment| %>
          <p><%= comment.author.name %>: <%= comment.text %></p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="pagination">
    Pagination
</div>

app/views/posts/new.html.erb
<h1 class="user_header_title">Create a Post</h1>
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<div class="post-container">
  <div class="post-details border">
    <div class="post-header">
      <h3>
        Post #<%= @post.title %> by <%= @user.name %>
      </h3>
      <%= button_to 'Like Post', user_post_likes_path(@user, @post), method: :post, class: 'like_post_btn'%>
      <% if can? :destroy, @post %>
        <%= button_to 'Delete Post', user_post_path(@user, @post), method: :delete, class: 'like_post_btn'%>
      <% end %>
      <p>
        Comments: <%= @post.comments_counter %> , Likes: <%= @post.likes_counter %>
      </p>
    </div>
    <p>
      <%= @post.text %>
    </p>
  </div>

  <div class="post-comments border">
    <% @post.comments.each do |comment| %>
      <p><%= comment.author.name %>: <%= comment.text %></p>
      <% if can? :destroy, comment %>
          <%= button_to 'Delete Comment', user_post_comment_path(@user, @post, comment), method: :delete, class: 'like_post_btn'%>
      <% end %>
    <% end %>
  </div>
</div>
<%= render 'comments/form' %>

app/views/users/_user_info.html.erb
<div class="user-home">
  <div class="user-photo border">
    <img scr="<%= user.photo%>" alt="<%= user.name%>">
  </div>

  <div class="user-details border">
    <h1 class="username">
      <%= user.name %>
    </h1>
    <p class="no-of-posts">
      Number of posts: <%= user.posts_counter %>
    </p>
  </div>
</div>

app/views/users/_user_post.html.erb
<div class="user-post-card">
  <h3>Post #<%= post.id %></h3>
  <div>
    <h4><%= post.title %></h4>
    <p><%= post.text %></p>
    <div class = "reactions">
      <span>Comments: <%= post.comments_counter %></span>
      <span>Likes: <%= post.likes_counter %></span>
      <%= link_to "View More", user_post_path(@user, post), class: "view_more_btn"%>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="home-page">
  <% @users.each do |user| %>
    <%= link_to user_path(user.id) do %>
      <%= render partial: 'user_info', locals: { user: user } %>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-show-post">
  <%= render partial: "user_info", locals: {user: @user} %>
  <div class="bio-post">
    <div class="border bio">
      <h3>Bio</h3>
      <p class="bio-text">
        <%= @user.bio %>
      </p>
    </div>
    <%= link_to "create a post", new_user_post_path(@user)%>
    <div class="user-posts">
      <% @user.recent_posts.each do |post| %>
        <%= link_to user_post_path(@user.id, post.id) do %>
          <%= render partial: "user_post", locals: {post: post} %>
        <% end %>
      <% end %>
    </div>
  <div>

  <div class="all-posts">
      <%= link_to user_posts_path(@user.id) do %>
        <p class="see-all-posts">See all posts</p>
      <% end %>
  </div>
</div>